- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.inputrc:
    ~/.shell:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/bin: bin/

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
