- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.hammerspoon:
    ~/.inputrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/bin: bin/
    ~/scripts: scripts/

- shell:
    - [git submodule sync --recursive, Syncing submodules]
    - [git submodule update --init --recursive, Updating submodules]
