tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "rylan12/blame"
tap "rylan12/development"
tap "rylan12/personal"
tap "rylan12/testing"
tap "rylan12/unpack-bottle"
tap "teamookla/speedtest"
brew "ack"
brew "openssl@1.1"
brew "sqlite"
brew "python@3.9"
brew "awscli"
brew "cmatrix"
brew "cowsay"
brew "doitlive"
brew "dos2unix"
brew "exa"
brew "fd"
brew "flake8"
brew "gettext"
brew "gh"
brew "pcre2"
brew "git"
brew "git-sizer"
brew "gnu-sed"
brew "p11-kit"
brew "libgpg-error"
brew "gnupg"
brew "ncurses"
brew "htop"
brew "hub"
brew "jq"
brew "lazygit"
brew "less"
brew "libuv"
brew "libwebsockets"
brew "lolcat"
brew "mas"
brew "mosquitto"
brew "nano"
brew "ncdu"
brew "nmap"
brew "node"
brew "openconnect"
brew "pipgrip"
brew "rbenv"
brew "ripgrep"
brew "shellcheck"
brew "so"
brew "thefuck"
brew "tiger-vnc"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "rylan12/personal/archey-macos"
brew "teamookla/speedtest/speedtest"
cask "balenaetcher"
cask "disk-inventory-x"
cask "github"
cask "hammerspoon"
cask "macdown"
cask "mactex-no-gui"
cask "notable"
cask "orka"
cask "vlc"
mas "DevCleaner", id: 1388020431
mas "Grammarly for Safari", id: 1462114288
mas "Honey", id: 1472777122
mas "RAR Extractor - The Unarchiver", id: 646295438
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "Trello", id: 1278508951
mas "WhatsApp", id: 1147396723
