#! /bin/bash
# alias: brew linux-dispatch
#:  * `linux-dispatch` [args...]
#:    `brew linux-dispatch` is an alias for `brew dispatch-build-bottle --linux --upload`
brew dispatch-build-bottle --linux --upload $*

